spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: testdb
    password: psw1234
  jpa:
    hibernate:
      dl-auto: create
  h2:
    console:
      enabled: true


## Abilita le funzionalità di sviluppo
#spring:
#  devtools:
#    enabled: true
#
## Configurazione del server web
#server:
#  port: 8080